name: Github Context

on:
  workflow_dispatch

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info about Github
        run: |
          echo "Repository details: ${{ github.repository }}"
          echo "Repo id: ${{ github.repository_id }}"
          echo "Repo url: ${{ github.repositoryUrl }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref details: ${{ github.ref }}"
          echo "Trigger event: ${{ github.event_name }}"
          echo "Run id: ${{ github.run_id }}"
          echo "Runner Number: ${{ github.run_number }}"

      - name: Examples
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "deploy"

      - name: Pull Request Trigger
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "trigger the workflow"
