name: Matrix

on: workflow_dispatch

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
    matrix:
     os:
      - ubuntu-latest
      - window-latest
     java-version: [17,21]  

 steps:
  - name: Setup Java JDK
    uses: actions/setup-java@v3.14.1
    with:
      java-version: ${{matrix.java-version}}

